### ISSUE TITLE
How to edit template on fly?

### ISSUE THREAD

**Issue by vetal20600** [epoupon/fileshelter#10]
What if I want to edit text of "**Terms of Service**" on the fly? Without recompiling sources with "**tos.xml**?
Any ideas? Put the whole text of "**tos.xml**" in to database? Maybe more elegant way?

**Comment by epoupon** [comment]
What do you mean exactly by on the fly?
If you edit the tos.xml file, changes will take effect for the new established connections.

I was planning to add a custom tos in the configuration file.
Something like that:
custom-tos = /path/to/custom/tos

However, that is not really on the fly since you would have to restart the application for the tos be updated.

**Comment by vetal20600** [comment]
On-the-fly means load the file "tos.xml" into stream.
Then read from stream to string, from string to WString, and finally load to WTextEdit.
Make changes, save in file "tos.xml".
However if everything is ok in the approach above I still have to recompile the sources and restart application to apply changes. I am looking the way how to avoid this.

**Comment by epoupon** [comment]
Here is what I propose:

1/ I put some code to use a custom ToS (this code will transform the txt file to an xml file)
2/ You make your own WTextEdit to edit the custom ToS file and you reuse the 1/ code to regenerate the xml file. It will be applied on the next connection.

What do you think?

**Comment by vetal20600** [comment]
So the basic idea is to upload/save ToS from txt file, not from database.
And your code can transform this text file with ToS to template.

I like it.

**Comment by vetal20600** [comment]
I made a very simple solution for non-big templates.
Just read template body as text to std::string, then apply it to template using _setTemplateText_.

**Comment by epoupon** [comment]
Hello,
Indeed it may be less intrusive to just set the template text. I will give it a try.
