### ISSUE TITLE
Fileshelter and WebToolkit 3.3.7

### ISSUE THREAD

**Issue by vetal20600** [epoupon/fileshelter#11]
Hello, as I see this 
`sudo apt-get install libwtdbosqlite-dev libwthttp-dev libwtdbo-dev libwt-dev`
installs prebuilt packages (version 3.3.4)
![screen shot 2017-03-30 at 15 03 14](https://cloud.githubusercontent.com/assets/4103746/24503293/225b2672-155a-11e7-859b-2e495ea2f274.png)
I want to update WebToolkit to version 3.3.7 to use new features of framework. Main question is: will it work ok?

**Comment by epoupon** [comment]
I guess it will.
The demo server is running using the 3.3.6 version.
Feel free to report any problem !

**Comment by epoupon** [comment]
It does compile with wt 3.3.7: nothing to do for this issue.
