### ISSUE TITLE
Deploy on non root URL

### ISSUE THREAD

**Issue by viharm** [epoupon/fileshelter#14]
Hi, this is a very good tool. Thanks for developing this.

I am trying to deploy FileShelter on a non-root URL behind a reverse proxy (Apache 2.4). However since I use this web server for other sites and web apps, I wish to deploy FileShelter under "/fileshelter", not the root (e.g., https://domain.tld/fileshelter).

I could not find a specific configuration option to specify web root, so it automatically navigates to https://domain.tld/home as default.

Is there a way to specify the web root?

Thanks in advance.

**Comment by epoupon** [comment]
Hello,

Please try the "deploy-path" option in the latest master branch.
I did not try using a reverse proxy, so please feel to reopen the issue if something is not working as expected.

**Comment by viharm** [comment]
Tried to pull and build from master. Unfortunately, it needs libzip version >=1.0.1, however I am running *Debian Jessie* with libzip version 0.11.2. Will have to test this on a *Stretch* VM.

**Comment by viharm** [comment]
Tried with `deploy-path = "/fileshelter";` option. Functionality works but the *Wt* resources are not correctly linked due to the virtual URL. Some example outputs are as follows.

I have created link to the *Wt* resources (`/usr/share/Wt/resources`) in the docroot (`/usr/local/src/fileshelter/docroot/resources`)

From fileshelter console output (notice duplicate `fileshelter` in URL)
```
"GET /fileshelter/fileshelter?wtd=evWkKaxHcZLGvwL1&request=resource&resource=ox1s283&rand=0 HTTP/1.1" 200 124
```

From page source at client end
```
<link href="../../resources/themes/bootstrap/3/bootstrap.css" rel="stylesheet" type="text/css">
<link href="../../resources/themes/bootstrap/3/wt.css" rel="stylesheet" type="text/css">
<link href="../../resources/moz-transitions.css" rel="stylesheet" type="text/css">
<link href="../../css/fileshelter.css" rel="stylesheet" type="text/css">
<link href="../../resources/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
```

This resource is not available at the relative path, as at that level is the root of the webserver. Probably just a fix on how the internal web server organises these resources.

Hope this helps :-)


-Viharm

**Comment by epoupon** [comment]
Hello,

Thanks for testing this. This is strange I cannot reproduce.
The sym link should have been created by the make install directive ?

**Comment by vectorselector** [comment]
same issue: 
Fatal error: failed loading /resources/themes/bootstrap/5/bootstrap.bundle.min.js
when clicking shared link (Firefox 119)
works OK in Brave
symlink is not getting created despite `deploy-path = "/fileshelter";`  in configuration.
otherwise, works OK under different deploy-path
