### ISSUE TITLE
HTTPS URLs behind reverse proxy

### ISSUE THREAD

**Issue by paulgalow** [epoupon/fileshelter#15]
Hi Emeric,

first of all thanks for your great contribution to the community. I think you have achieved a great balance between simple user interface and great feature set. 

I have a test installation of it running behind a Caddy web server in reverse proxy mode. Everything runs just great however I'd like to suggest a small improvement: 

Since my proxy does TLS termination all HTML links are rendered as TLS by default. However once you upload a file the generated URLs for "Public download link" and "Private edit link" are displayed as HTTP only since Fileshelter is not aware of the TLS termination happening at the proxy level. So I'd suggest a boolean option for "fileshelter.conf" such as "tls-urls" which toggles TLS URL rendering on or off.

Thanks,
Paul

**Comment by epoupon** [comment]
Hello,

Thanks for your comments!

For your problem, could you please have a look at the issue #4 and tell me if it solved the problem?

**Comment by paulgalow** [comment]
Thanks for your quick reply and for pointing me towards issue #4. In fact all URLs are correctly rendered as HTTPS hyperlinks but the URL strings on the page are only displayed as HTTP. Here's some plain HTML to illustrate what I mean:

Desired behaviour:
`<p>Public download link: <a href="https://path/to/file">https://path/to/file</a></p>`

Current behaviour:
`<p>Public download link: <a href="https://path/to/file">http://path/to/file</a></p>`

In my fileshelter.conf I do have "tls-enable = false;". Hope this is of help.

**Comment by epoupon** [comment]
Hey,

Actually I was refering to the "X-Forwarded-Proto" option.
I guess the "transparent" preset would do the job for your server (https://caddyserver.com/docs/proxy)?

**Comment by paulgalow** [comment]
Exactly. This is what I'm running with the Caddy proxy directive.

```
# Caddyfile

example.com {
  tls name@example.com

  header / {
    # Prevent search bots from indexing
    X-Robots-Tag "noindex, nofollow, noarchive, nosnippet, noodp, nocache, notranslate, noimageindex, noydir"
    # Enable HTTP Strict Transport Security (HSTS) to force clients to always
    # connect via HTTPS (do not use if only testing)
    Strict-Transport-Security "max-age=31536000;"
    # Enable cross-site filter (XSS) and tell browser to block detected attacks
    X-XSS-Protection "1; mode=block"
    # Prevent some browsers from MIME-sniffing a response away from the declared Content-Type
    X-Content-Type-Options "nosniff"
    # Disallow the site to be rendered within a frame (clickjacking protection)
    X-Frame-Options "SAMEORIGIN"
  }

  proxy / fileshelter:5091 {
    transparent
  }

  ratelimit / 500 1000 minute
  maxrequestbody 1GB
  gzip
  log stdout
  errors stdout

  timeouts {
    read   360m
    header 30m
    write  30m
    idle   30m
  }
}
```

**Comment by epoupon** [comment]
What do you see if you capture traffic after the reverse proxy?

Here is what I got when I capture on lo from some mobile using a 4G connection:

> GET /home HTTP/1.0
> Host: XXX.XXX.com
> X-Real-IP: X.X.X.X
> X-Forwarded-For: X.X.X.X
> X-Forwarded-Proto: https
> Connection: close
> Cache-Control: max-age=0
> ...

**Comment by paulgalow** [comment]
Can confirm. I'm running in two Docker containers (I'm planning to post my Docker setup once I can carve out some time...). Here's what I'm capturing on eth0 with tcpflow inside a debian:jessie-slim Docker container running Fileshelter.

```
GET /home HTTP/1.1
Host: example.com
X-Forwarded-For: X.X.X.X
X-Forwarded-Proto: https
X-Real-Ip: X.X.X.X

HTTP/1.1 200 OK
Date: Thu, 3 May 2017 20:23:24 GMT
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: SAMEORIGIN
Content-Encoding: gzip
Transfer-Encoding: chunked
```

So URLs are successfully translated into https. It's only the page that comes up after you have uploaded a file headlined "Share successfully created!" that displays http URLs. See screenshot attached. Hope this of help. Thanks for looking into this!

![share_successfully_created](https://cloud.githubusercontent.com/assets/10907468/25680527/6fbf918e-3051-11e7-83f0-484422e0e9ca.png)

**Comment by epoupon** [comment]
Hello,

By the way, did you set "behind-reverse-proxy" to" true" in the fileshelter.conf file?

**Comment by paulgalow** [comment]
Yes, I did. My fileshelter.conf looks like this:

```
# Working directory (must have write privileges)
working-dir = "/var/fileshelter";

# Max validity duration for a share, in days. Must be greater than 0
max-validity-days = 30;

# Max number of downloads for a share. 0 means unlimited
max-validity-hits = 30;
# Proposed number of downloads for a share
default-validity-hits = 10;

# Maximum size of the files to be uploaded, in megabytes
max-file-size = 1000;

# Listen port/addr of the web server
listen-port = 5091;
listen-addr = "0.0.0.0";
behind-reverse-proxy = true;

# If enabled, these files have to exist and have correct permissions
tls-enable = false;
#tls-cert = "/path/to/crt";
#tls-key = "/path/to/key";
#tls-dh = "path/to/dh2048.pem";

# Application settings
app-name = "Example";

# ToS settings
tos-org = "Example Co";
tos-url = "example.com";
tos-support-email = "name@example.com";

# Path to the resources used by the web interface
docroot = "/usr/share/fileshelter/docroot/;/resources,/css,/images,/favicon.ico";
approot = "/usr/share/fileshelter/approot";

# Bcrypt count parameter used to hash passwords
bcrypt-count = 12;
```

**Comment by epoupon** [comment]
I think there may be a bug that would be fixed in wt 3.3.5.
Which version do you use?
Could you by chance update your wt version?

**Comment by paulgalow** [comment]
That sounds promising. I'm running wt 3.3.3 which is the [current version on Debian Jessie](https://packages.debian.org/stable/allpackages).

```
# debian:jessie-slim

$ apt list \
  libboost-dev \
  libwtdbosqlite-dev \
  libwthttp-dev \
  libwtdbo-dev \
  libwt-dev \
  libconfig++-dev \
  libzip-dev  

Listing... Done
libboost-dev/stable,now 1.55.0.2 amd64 [installed]
libconfig++-dev/stable,now 1.4.9-2 amd64 [installed]
libwt-dev/stable,now 3.3.3+dfsg-4.1 amd64 [installed]
libwtdbo-dev/stable,now 3.3.3+dfsg-4.1 amd64 [installed]
libwtdbosqlite-dev/stable,now 3.3.3+dfsg-4.1 amd64 [installed]
libwthttp-dev/stable,now 3.3.3+dfsg-4.1 amd64 [installed]
libzip-dev/stable,now 0.11.2-1.2 amd64 [installed]
```

Will try Debian Stretch soon which is [currently shipping with wt 3.3.6](https://packages.debian.org/testing/allpackages). Will get back to you then... Thanks for your support!

**Comment by paulgalow** [comment]
Finally got around to trying out debian:stretch-slim and the updated wt packages (currently running v3.3.6). You were absolutely right, apparently the bug has been solved. 

I've come across another issue trying to delete shares though but will open a separate issue for that. Thanks again!

**Comment by epoupon** [comment]
Thanks for testing this!
Please feel free to report bugs to make this soft better :)

**Comment by paulgalow** [comment]
Thanks for figuring out the issue and even more thanks for sharing FileShelter with us. Will get back to you soon ;-)
