### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jguida** [epoupon/fileshelter#2]
I do all the installation process according to their new instructions without errors, but when running fileshelter get the following error:

[root@centos7 ~]# fileshelter 
ARG = fileshelter
ARG = --config=/var/fileshelter/wt_config.xml
ARG = --docroot=/usr/share/fileshelter/docroot/;/resources,/css,/images,/favicon.ico
ARG = --approot=/usr/share/fileshelter/approot
ARG = --http-port=5091
ARG = --http-address=0.0.0.0
INFO: Opened log file (/var/fileshelter/fileshelter.log).
Segmentation fault
[root@centos7 ~]#

**Comment by epoupon** [comment]
Well, this is strange.
Could you please run using gdb  and paste the backtrace here?
Something like that:
gdb fileshelter 
run
*Crash occurs*
bt

**Comment by jguida** [comment]
[root@centos7 ~]# gdb fileshelter 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/fileshelter...done.
(gdb) 
(gdb) 
(gdb) 
(gdb) run
Starting program: /usr/bin/fileshelter 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
ARG = /usr/bin/fileshelter
ARG = --config=/var/fileshelter/wt_config.xml
ARG = --docroot=/usr/share/fileshelter/docroot/;/resources,/css,/images,/favicon.ico
ARG = --approot=/usr/share/fileshelter/approot
ARG = --http-port=5091
ARG = --http-address=0.0.0.0
INFO: Opened log file (/var/fileshelter/fileshelter.log).

Program received signal SIGSEGV, Segmentation fault.
push (h=0x6aab20, this=0x6aab48) at /usr/include/boost/asio/detail/op_queue.hpp:110
110	      op_queue_access::next(back_, h);
Missing separate debuginfos, use: debuginfo-install boost-date-time-1.53.0-25.el7.x86_64 boost-filesystem-1.53.0-25.el7.x86_64 boost-program-options-1.53.0-25.el7.x86_64 boost-random-1.53.0-25.el7.x86_64 boost-regex-1.53.0-25.el7.x86_64 boost-signals-1.53.0-25.el7.x86_64 boost-system-1.53.0-25.el7.x86_64 boost-thread-1.53.0-25.el7.x86_64 glibc-2.17-106.el7_2.8.x86_64 libconfig-1.4.9-5.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libicu-50.1.2-15.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  push (h=0x6aab20, this=0x6aab48) at /usr/include/boost/asio/detail/op_queue.hpp:110
#1  init_task (this=0x6aaac0) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:129
#2  init_task (this=<optimized out>) at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:145
#3  deadline_timer_service (io_service=..., this=0x6a6938)
    at /usr/include/boost/asio/detail/deadline_timer_service.hpp:62
#4  deadline_timer_service (io_service=..., this=0x6a6910)
    at /usr/include/boost/asio/deadline_timer_service.hpp:72
#5  boost::asio::detail::service_registry::create<boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > > (owner=...)
    at /usr/include/boost/asio/detail/impl/service_registry.hpp:81
#6  0x0000000000439129 in boost::asio::detail::service_registry::do_use_service (this=0x6a2040, key=..., 
    factory=factory@entry=0x4392b0 <boost::asio::detail::service_registry::create<boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > >(boost::asio::io_service&)>)
    at /usr/include/boost/asio/detail/impl/service_registry.ipp:123
#7  0x0000000000436e28 in use_service<boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > > (this=<optimized out>)
    at /usr/include/boost/asio/detail/impl/service_registry.hpp:48
#8  use_service<boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > > (ios=...) at /usr/include/boost/asio/impl/io_service.hpp:33
#9  basic_io_object (io_service=..., this=0x7fffffffe3c0) at /usr/include/boost/asio/basic_io_object.hpp:90
#10 basic_deadline_timer (io_service=..., this=0x7fffffffe3c0)
    at /usr/include/boost/asio/basic_deadline_timer.hpp:145
#11 Database::Cleaner::Cleaner (this=0x7fffffffe390, connectionPool=...) at ../../src/database/DbCleaner.cpp:37
#12 0x0000000000429cfd in main (argc=<optimized out>, argv=0x7fffffffe638) at ../../src/main/main.cpp:155
(gdb)

**Comment by epoupon** [comment]
Just to be sure:
Are you sure you successfully removed previous manual installations of wt and boost( .so files, includes,etc.) before rebuilding everything?

**Comment by epoupon** [comment]
Sorry my bad, I mis wrote the CentOS installation instructions in the readme.
Could you please recompile wt again (it may be a good idea to rm the build directory before) and tell me if this fixes the problem?

Don't hesitate to reopen this issue if this is not the case.

**Comment by jguida** [comment]
ok I will try again to compile wt

**Comment by jguida** [comment]
Working, thank you very much
