### ISSUE TITLE
Error trying to delete uploaded share

### ISSUE THREAD

**Issue by paulgalow** [epoupon/fileshelter#20]
Hi Emeric,

as briefly mentioned I have finally managed to publish my Docker workflow to get FileShelter running with Caddy easily. There is one issue I have come across though: I can't delete uploaded shares after upgrading to wt 3.3.6 (running on Debian Stretch Slim) running FileShelter v2.0.1.

**How to reproduce?**
Using the Docker workflow provided (https://github.com/paulgalow/fileshelter-docker), upload a file. Then hit the red delete button.

**Erroneous behaviour:**

- First error message issued by web browser (pop up):
`Wt internal error; code: undefined, description: url.indexOf is not a function`

- Second message issued by web browser (pop up):
`Wt internal error; code: undefined, description: tr.size is not a function`

After hitting OK a second time the page stays in a "Loading..." stage indefinitely. Could this be related to some changes in wt?

Regards,
Paul

**Comment by epoupon** [comment]
This is strange, I never hit such an issue with wt 3.3.6 nor 3.3.7 before.
I will try the packaged version of wt on stretch to check to check that.

**Comment by greecemunky** [comment]
Getting the same error. Fresh install of Debian Stretch, installed FileShelter from source as directed, libwt* version 3.3.6+dfsg-1.1 .

**Comment by epoupon** [comment]
Ok this is indeed bad news :(
Can you by chance test using a wt install from source? 
I will try a fresh Debian Stretch install myself to figure this out.

**Comment by epoupon** [comment]
I reproduced the problem. I opened a discussion on this with the wt guys here: http://redmine.webtoolkit.eu/boards/2/topics/13573

**Comment by epoupon** [comment]
And a debian bug report here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884540

**Comment by epoupon** [comment]
It seems the wt no longer has a maintener on debian/ubuntu. Therefore, I can just tell you to install Wt by hand to solve the problem.

By the way, as you have to install wt by hand, I recommend that fileshelter switches to a newer version of wt, wt4 (the develop branch is already working with wt4, I will merge it to master soon).
