### ISSUE TITLE
Feature request: Set default validity period

### ISSUE THREAD

**Issue by paulgalow** [epoupon/fileshelter#21]
I'd love to set a default for "validity period". Currently this is always set to 1 day. So an option like "default-validity-days" in fileshelter.conf could come in really handy.

Perhaps this is of interest.

**Comment by epoupon** [comment]
Hello,
This is indeed planned, I already have a branch with this feature!

**Comment by paulgalow** [comment]
Sorry, didn't see that. Looking forward to it!

**Comment by epoupon** [comment]
No problem, I have not pushed the branch on github :)

**Comment by paulgalow** [comment]
Thanks for implementing this. I've updated my Docker workflow to also support the latest FileShelter version. So essentially people can now choose to run your latest official release, i.e. currently v2.0.1 or they can decide to run the latest version based on your current GitHub repository. Hope this is useful to someone.
