### ISSUE TITLE
Can not add record to new table

### ISSUE THREAD

**Issue by vetal20600** [epoupon/fileshelter#23]
I want to use second table to keep additional data there.
I am using the same approach ad described in "Share.cpp", "Share.hpp", "DbHandler.cpp", "DbHandler.hpp".
This is how it looks:
![screen shot 2017-05-20 at 04 03 36](https://cloud.githubusercontent.com/assets/4103746/26271660/79f6bba6-3d11-11e7-9778-33249e463280.png)

I am trying to add data to new table:
![screen shot 2017-05-20 at 04 07 01](https://cloud.githubusercontent.com/assets/4103746/26271690/ddb6a58e-3d11-11e7-8821-a9b3c6846b1c.png)

These lines do not execute. Seems like "transaction.commit();" silently fails. And question is why? I can not get a clue.
```
	std::cout << "it success" << std::endl;
	std::cout << "Yes, we are here. Done3___________________ " << std::endl;
```

**Comment by epoupon** [comment]
If you modify the database schema, make sure to remove the previous database file since there is no migration.
How can you be sure it fails? Have you inspected the database file using the sqlite3 command line utility?
You can also uncomment "connection->setProperty("show-queries", "true")" in dbhandler to make sure the sql command are fired.

**Comment by vetal20600** [comment]
I downloaded "fileshelter.db", then I opened it using sql.lite editor, then I added new table using this script:
```
CREATE TABLE `mydata` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`transaction_id`	TEXT,
	`time_when_attached`	TEXT,
	`issuccess`	INTEGER,
	`file_password`	TEXT
);
```
Saved "fileshelter.db". Uploaded back to server.
____
You say there is no migration, so that is why new table does not accept new records? Can you give any suggestions what to do if I want to keep "share" table in current state with current data and use "mydata" table at same time?

I can be sure because that there is no new data in "mydata" table because I did inspect database file using sql.lite editor after actions described above.

**Comment by epoupon** [comment]
Tables are automatically created if the database does not exist.
You can rename the current database, relaunch the app, get the generated database, and use the .schema command using sqlite3 tool to get the actual table created.
You also have to make sure to map the class members to the sqlite tables (see persist template method)

**Comment by vetal20600** [comment]
Thank you!
What I did:
1. Rename old database file to "fileshelterlas.db".
2. Relaunch application.
3. Open new database file in sql.lite editor. 
5. Export "mydata" table schema.
6. Import "mydata" table schema to old database file.
7. Rename old database file "fileshelterlas.db" to "fileshelter.db".
8. Relaunch application.
9. Now it works as expected!

**Comment by epoupon** [comment]
You're welcome!
