### ISSUE TITLE
Add Unicode file name

### ISSUE THREAD

**Issue by Madji** [epoupon/fileshelter#24]
Please add unicode support filename
![1](https://user-images.githubusercontent.com/2238714/30799368-4f080998-a1e5-11e7-824d-4ac5cef52312.png)

**Comment by epoupon** [comment]
This problem should be already fixed in the master branch (see #16) 
Which version are you running?

**Comment by Madji** [comment]
https://github.com/epoupon/fileshelter/releases/download/v2.0.1/fileshelter_2.0.1-1_amd64.deb

this

**Comment by Madji** [comment]
Thank you

**Comment by epoupon** [comment]
I will make a new minor public release soon so that you can get the recent bug fixes
