### ISSUE TITLE
missing stylesheets

### ISSUE THREAD

**Issue by WilliButz** [epoupon/fileshelter#27]
### Expected behaviour:
A freshly compiled instance of fileshelter looks like the demo instance.

### Observed behaviour:
Apparently the bootstrap and font-awesome stylesheets are neither provided in the repo nor fetched during build or runtime, which leads to 404 Responses when one tries to use fileshelter and thus the fileshelter page looks incomplete:

```ARG = ./result/bin/fileshelter
ARG = --config=/var/lib/fileshelter/workdir/wt_config.xml
ARG = --docroot=/var/lib/fileshelter/docroot;/resources,/css,/images,/favicon.ico
ARG = --approot=/var/lib/fileshelter/approot
ARG = --deploy-path=/
ARG = --http-port=5091
ARG = --http-address=0.0.0.0
INFO: Opened log file (/var/lib/fileshelter/workdir/fileshelter.log).
127.0.0.1 - - [2017-Dec-22 13:40:17.885931] "GET /home HTTP/1.1" 200 3741
127.0.0.1 - - [2017-Dec-22 13:40:17.992152] "POST /?wtd=Xce0k99EP0oXWDga HTTP/1.1" 200 76
127.0.0.1 - - [2017-Dec-22 13:40:18.011929] "GET /resources/themes/bootstrap/3/bootstrap.css HTTP/1.1" 404 85
127.0.0.1 - - [2017-Dec-22 13:40:18.012637] "GET /resources/font-awesome/css/font-awesome.min.css HTTP/1.1" 404 85
127.0.0.1 - - [2017-Dec-22 13:40:18.012833] "GET /css/fileshelter.css HTTP/1.1" 200 32
127.0.0.1 - - [2017-Dec-22 13:40:18.012990] "GET /resources/moz-transitions.css HTTP/1.1" 404 85
127.0.0.1 - - [2017-Dec-22 13:40:18.013029] "GET /resources/themes/bootstrap/3/wt.css HTTP/1.1" 404 85
127.0.0.1 - - [2017-Dec-22 13:40:18.170322] "GET /home?wtd=GGArnrb52kcnFTGb&sid=1398964801&webGL=true&scrW=1920&scrH=1080&tz=60&htmlHistory=true&deployPath=%2F&request=script&rand=527347002 HTTP/1.1" 200 42347
127.0.0.1 - - [2017-Dec-22 13:40:18.261433] "POST /?wtd=GGArnrb52kcnFTGb HTTP/1.1" 200 50
```

The only stylesheet provided is `/docroot/css/fileshelter.css`

The missing ones are expected to be found under:
* `/docroot/resources/font-awesome/css/font-awesome.min.css`
* `/docroot/resources/font-awesome/fonts/fontawesome-webfont.woff2`
* `/docroot/resources/moz-transitions.css`
* `/docroot/resources/themes/bootstrap/3/bootstrap.css`
* `/docroot/resources/themes/bootstrap/3/wt.css`

**Comment by epoupon** [comment]
Hello,

It looks like you use a non standard wt path.
Is the /var/lib/fileshelter/docroot directory is a link or a copy of the  wt's default resource directory?

**Comment by WilliButz** [comment]
@epoupon It's a copy of the included `docroot` and it contains the provided `css` subdirectory with `fileshelter.css` inside. The other stylesheets in the `resources` subdirectory as well as the directory itself are missing as stated above.
Fileshelter itself is working properly, it's just not displayed right due to the missing stylesheets.

**Comment by WilliButz** [comment]
@epoupon But I see what you mean. It was not clear to me that the missing stylesheets are provided by the WT package. Maybe you could add a note about that in the readme, then I would consider this issue closed.

👍

**Comment by epoupon** [comment]
Ok, I will fix that!
Is it working properly now?

**Comment by WilliButz** [comment]
When I use the stylesheets provided by Wt, it works properly 👍
