### ISSUE TITLE
How to add multiple user password?

### ISSUE THREAD

**Issue by openaspace** [epoupon/fileshelter#28]
HI, 
your software is wonderful!

I want to allow the upload to different peoples , how to add multiple users upload password?

Thank you.

**Comment by openaspace** [comment]
I have tried adding other users dividing each one by  ";" or adding each user to a new line, but i see that is not projected to works with more than only one user.

**Comment by epoupon** [comment]
Hi,
Currently, there is indeed a single optional password to be able to upload.
I am curious, what would be the benefits of multiple upload passwords?

I guess we could easily allow multiple upload passwords, I don't think it is that worse in term of security compared to a single password.

**Comment by openaspace** [comment]
Hi.
I have some video makers collaborators, that needs to ship files to me for a defined period. When the collaboration end, I need to close to a single person the file upload service.

Thanks.

**Comment by epoupon** [comment]
Ok, we could do it. But since there is no user management, would you accept to stop/start the service in order to reload the passwords? It would of course interrupt all active downloads/uploads.

**Comment by openaspace** [comment]
Hi. You're big :)
I had not thought of this possible problem, but it does nothing .... of all
the systems I've tested, yours is the best! :)

Il gio 28 nov 2019, 19:49 Emeric POUPON <notifications@github.com> ha
scritto:

**Comment by openaspace** [comment]
...as also to possibility to select up to 10 files to upload at the same time...
and download as .zip file or one bye one

**Comment by epoupon** [comment]
You can already upload multiple files, a zip file will be created server side (however you cannot download individual files once they are zipped)
