### ISSUE TITLE
build error on ubuntu

### ISSUE THREAD

**Issue by muralikodali** [epoupon/fileshelter#29]
checking dependency style of g++... gcc3
../configure: line 3410: syntax error near unexpected token `libzip,'
../configure: line 3410: `PKG_CHECK_MODULES(libzip, libzip >= 0.11)'

I am getting the error even after installing all dependencies ( installed libzip from https://github.com/nih-at/libzip )

**Comment by epoupon** [comment]
Which version of ubuntu are you using?
You can find an installation example for bionic here: https://github.com/epoupon/fileshelter/blob/master/.travis.yml
I guess you don't need to manually install libzip on newer version

**Comment by muralikodali** [comment]
ubuntu version is 18.04

libzip installed in /usr/local/ folder. i have commented line 3410 of configure file i.e; PKG_CHECK_MODULES(libzip, libzip >= 0.11)'.

After installing wt , when tried to configure and run make command it is **giving following errors**.

Making all in src
make[1]: Entering directory '/home/XXXX/Downloads/fileshelter/build/src'
g++ -DHAVE_CONFIG_H -I. -I../../src -I../src/config    -std=c++17 -I../../src/ui  -g -O2 -MT fileshelter-main.o -MD -MP -MF .deps/fileshelter-main.Tpo -c -o fileshelter-main.o `test -f '../../src/main/main.cpp' || echo '../../src/'`../../src/main/main.cpp
../../src/main/main.cpp:20:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:460: recipe for target 'fileshelter-main.o' failed
make[1]: *** [fileshelter-main.o] Error 1
make[1]: Leaving directory '/home/XXXX/Downloads/fileshelter/build/src'
Makefile:467: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by epoupon** [comment]
Hello,

Ok I see. Actually you need gcc version >= 8, and 18.04 ships with gcc v7.4.
I think the easiest way to use fileshelter is then to use the docker file instead. @paulgalow made an image some times ago (see readme). I may create an up-to-date image myself if needed.

**Comment by paulgalow** [comment]
Hi everyone,

I have just [released a new Docker image](https://hub.docker.com/repository/docker/paulgalow/fileshelter). It is now based on Debian Buster Slim and contains the current version of FileShelter v4.0.1. Thanks for reminding me @epoupon ;-)
