### ISSUE TITLE
Safari adds "txt" file extension to downloaded files

### ISSUE THREAD

**Issue by paulgalow** [epoupon/fileshelter#30]
Hi @epoupon ,

I have been running into an issue for a while where Safari adds a 'txt' file extension to every downloaded file. I have tested this on macOS 10.13.X and 10.14.6 as well as iOS 13.3. The issue does not come up using Chrome or Firefox. My guess is that Safari's behaviour is due to the HTTP Content-Type response header being set to "text/plain".

**How to reproduce**
Upload a test file to the [demo instance](https://fileshelter.demo.poupon.io/) and download it using Safari. Inspect the downloaded file. It has a "txt" extension attached to it.

**Possible remediation**
The HTTP response header when downloading a file is set to ```Content-Type: text/plain```. Changing it to ```Content-Type: application/octet-stream``` [might fix this behaviour](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Configuring_server_MIME_types).

I would like to submit a pull request but could not find the settings in your source code. Sorry.

Thanks for all your work!

**Comment by epoupon** [comment]
Hi!
Thanks for reporting!
As far as I remember I decided not to put a mime type since I cannot be sure of the underlying file type. However I was not aware that the Wt library would put a "text/plain" mime type by default.

**Comment by paulgalow** [comment]
Thanks for fixing this so quickly. In my testing the issue has been fixed.  I have just updated the [Docker image](https://hub.docker.com/repository/docker/paulgalow/fileshelter).
