### ISSUE TITLE
Percentage uploaded doesn't work

### ISSUE THREAD

**Issue by suckerfish** [epoupon/fileshelter#32]
It's at 0% until nearly the last moment. Then it fills up smoothly/linearly at the end. It doesn't reflect actual progress on upload. 

See screenshot here with 'actual' progress in bottom left corner of window. 

https://imgur.com/a/1ruiGf4

**Comment by epoupon** [comment]
Yes indeed. I am currently rewriting this part.

**Comment by epoupon** [comment]
By the way, do you use a proxy?
Actually I had this kind of behavior with a proxy bufferring the whole file.

**Comment by suckerfish** [comment]
Yep. Through Nginx.

**Comment by epoupon** [comment]
Do you use rules like:
```
    proxy_request_buffering off;
    proxy_buffering off;
```
?

**Comment by suckerfish** [comment]
I use nginx proxy manager which keeps a lot of this behind the scenes. However I did find this in the nginx.conf file it includes for everything by default.

```
proxy_cache                   off;
	proxy_cache_path              /var/lib/nginx/cache/public  levels=1:2 keys_zone=public-cache:30m max_size=192m;
	proxy_cache_path              /var/lib/nginx/cache/private levels=1:2 keys_zone=private-cache:5m max_size=1024m;
	log_format proxy '[$time_local] $upstream_cache_status $upstream_status $status - $request_method $scheme $host "$request_uri" [Client $remote_addr] [Length $body_bytes_sent] [Gzip $gzip_ratio] [Sent-to $server] "$http_user_agent" "$http_referer"';
```

**Comment by suckerfish** [comment]
I use Nginx Proxy Manger which hides a lot of this. I checked the internal nginx.conf file it uses and there are no settings for buffering defined.

**Comment by epoupon** [comment]
Ok then I guess it is likely to buffer the file in some way. What was the file size?

**Comment by gogorz** [comment]
I can confirm. Uploading a 1mb image makes the progress bar stuck at 0%.

**Comment by epoupon** [comment]
Did you try to remove buffering on nginx? (See example in readme)

**Comment by gogorz** [comment]
I used the example in readme.

**Comment by cwirz** [comment]
this seems fixed. i tried the solution with this nginx config and it worked!

```
server {
    listen 80;

    server_name myserver.org;

    access_log            /var/log/nginx/myserver.access.log;

    proxy_request_buffering off;
    proxy_buffering off;
    proxy_buffer_size 4k;
    client_max_body_size 256M; # Make the number the same as 'max-file-size' in fileshelter.conf

    location / {

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

      proxy_pass          http://localhost:5082;
      proxy_read_timeout  120;
    }
}
```

**Comment by enekux** [comment]
Hi I am still having problems with this, any ideas why is this happening? Thank you

**Comment by epoupon** [comment]
Hello!
Maybe your proxy buffers the file? How is it configured?
