### ISSUE TITLE
Upload Timeout

### ISSUE THREAD

**Issue by Blackneron** [epoupon/fileshelter#35]
Hi,

If I want to upload a file of 2.6 GB there is a timeout. The log states (there are only 2 lines):

```
[2020-Jun-13 08:17:14.146] 881 [/ TZ1U3U0Bqi2eZRP6] [info] "WebController: timeout: expiring"
[2020-Jun-13 08:17:14.147] 881 [/ TZ1U3U0Bqi2eZRP6] [info] "Wt: session destroyed (#sessions = 1)"
```

How can I extend the time?

Thanks and have a nice day!

**Comment by epoupon** [comment]
Hi!
Could you describe what is happening?
Was the progress bar filled to 100%?

**Comment by Blackneron** [comment]
Hi and sorry about the missing information!
Yes, the file was uploaded and the progress bar showed 100%. Sthe spinner was still rotating for about 5 minutes. After that the screen returned to the homescreen where you can add files and start a new upload. The download links were not displayed. I tied this on a Raspberry Pi 3B (1GB RAM) and also on a new Raspberry 4 (4 GB RAM). The outcome is the same. It seems that the ram usage is not the problem and the CPU power neither. CPU usage was not very high on the Pi4 (about 30%). Thanks a lot!

**Comment by epoupon** [comment]
Ok, it somewhat looks like #31 :)
I am working on a rewrite of this part.

**Comment by Blackneron** [comment]
OK, thanks a lot, I will wait :-)
