### ISSUE TITLE
Add support to Wt 4.5

### ISSUE THREAD

**Issue by lollofra** [epoupon/fileshelter#44]
In [Wt 4.5](https://www.webtoolkit.eu/wt/news/2020/12/15/wt_4_5_0___3_7_1_released) the `<behind-reverse-proxy>` was deprecated and replaced with `<trusted-proxy-config>` so fileshelter don't work behind proxy with wt 4.5 and make this warning:

`[2021-Jan-03 20:45:56.953] 47646 - [warning] "config: The behind-reverse-proxy configuration option is deprecated, use a <trusted-proxy-config> block instead"`

**Comment by epoupon** [comment]
Thanks for reporting this!
According to the release notes:
>  When <behind-reverse-proxy> is set to true, the behavior stays the same as it was before

So, is it really broken or is it just a warning?

**Comment by lollofra** [comment]
Yes, it'works! I've noticed that in the first nginx configuration example is used the port 5082 I've changed it with the port 5091 and now it works just fine.

**Comment by epoupon** [comment]
trusted-proxy-config implemented in v5 branch
