### ISSUE TITLE
Cleaning of expired shares not working

### ISSUE THREAD

**Issue by siberianhuskys** [epoupon/fileshelter#45]
Hello,

first, great file sharer. It is really simple while offering everything needed. Well done!

However, for me the auto cleaning of expired shares does not work. If I understand the source code correct, the auto cleaning should occur every 6 hours. My Setup is Debian in an LXC container.
On 2021-Jan-11 around 18:15 I upload a small test file with a life time of one hour. So expiration date is according to the private link `Mon Jan 11 19:15:34 2021 UTC`.

This morning, the private and public link are still accessible. (It shows that the file is expired).

Checking the log, I can see at least two attempts to cleaning expired shares (see below), but as described above it is not deleted.
If I understand correctly, the file should be already deleted in the file system.

```
Jan 12 01:15:05 fileshelter fileshelter[293]: [2021-Jan-12 01:15:05.601] 293 - [info] - [DB] Cleaning expired shares...
Jan 12 01:15:05 fileshelter fileshelter[293]: [2021-Jan-12 01:15:05.601] 293 - [info] - [DB] Current number of shares: 1
Jan 12 01:15:05 fileshelter fileshelter[293]: [2021-Jan-12 01:15:05.602] 293 - [info] - [DB] Cleaning expired shares: complete!
Jan 12 07:15:05 fileshelter fileshelter[293]: [2021-Jan-12 07:15:05.602] 293 - [info] - [DB] Cleaning expired shares...
Jan 12 07:15:05 fileshelter fileshelter[293]: [2021-Jan-12 07:15:05.602] 293 - [info] - [DB] Current number of shares: 1
Jan 12 07:15:05 fileshelter fileshelter[293]: [2021-Jan-12 07:15:05.602] 293 - [info] - [DB] Cleaning expired shares: complete!
```

Small feature or improvement: It would be good to add the 6 hour cycle in the README. And maybe have the frequency of the cleaning as an option in the config (every X hour)?

Best regards

**Comment by epoupon** [comment]
Hi!
Indeed this is confusing.
Actually, a share is really deleted 24 hours after it expired. This delay is used to continue serving a file that has been requested before expiracy (same connection). It could have been done using a refcount but it was just easier this way.
Do you confirm this behavior?

**Comment by siberianhuskys** [comment]
Hi,
yes, I can confirm. After 24 hours the files are deleted. Thanks.

May I recommend to then update the readme to clarify this for other users?
Maybe after your sentence: "Once the expiry date or the download limit is reached, the download is no longer available and the file is deleted."
Add: "(The file is actually deleted 24 hours after the expiry date in order to allow previously started downloads to complete. Note, the check for which files to delete is done every 6 hours, i.e., in the worst case a file is actually deleted from the server 30 hours after the expiry date.)"

**Comment by epoupon** [comment]
Yes, that sounds good 👍
