### ISSUE TITLE
docroot and approot in custom conf file not working

### ISSUE THREAD

**Issue by sanderkwantes** [epoupon/fileshelter#5]
I have created a custom .conf file in /etc/ folder, as upgrades are overwriting the config file.
The customised TOS settings work fine, but it seems Fileshelter doesn't respect the config defined docroot and approot. Fileshelter still takes the default docroot and approot (as in /usr/share/fileshelter).

Below the relevant part of my redacted config file
```
# Path to the resources used by the web interface
docroot = "/usr/share/<redacted>/docroot/;/resources,/css,/images,/favicon.ico";
approot = "/usr/share/<redacted>/approot";
```
Below my redacted systemd file:
```
[Unit]
Description=<redacted>

[Service]
ExecStart=/usr/bin/fileshelter /etc/<redacted>.conf
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by epoupon** [comment]
Could you please run 'fileshelter /etc/<redacted>.conf' manually and paste the ARG lines that are printed in the console?

As an example, here is what I get:

```
$ ./src/fileshelter  ~/fileshelter-dev.conf
ARG = ./src/fileshelter
ARG = --gdb
ARG = --config=/storage/emeric/fileshelter-dev/wt_config.xml
ARG = --docroot=/storage/emeric/fileshelter-dev/usr/share/fileshelter/docroot/;/resources,/css,/images,/favicon.ico
ARG = --approot=/storage/emeric/fileshelter-dev/usr/share/fileshelter/approot
ARG = --http-port=5093
ARG = --http-address=0.0.0.0
INFO: Opened log file (/storage/emeric/fileshelter-dev/fileshelter.log).
```


BTW, what file(s) did you modify?

**Comment by sanderkwantes** [comment]
I think i didn't restart the systemd service initially. I cannot replicate the issue again. Everything works as expected.

**Comment by epoupon** [comment]
I was thinking about a New setting in the configuration file to specify a path to a custom TOS.
I am wondering if you wanted an alternate docroot for that usage?
