### ISSUE TITLE
Files don't auto-delete

### ISSUE THREAD

**Issue by antoine2tt** [epoupon/fileshelter#55]
Hello ! 

i uploaded 4 files to my Fileshelter, set them to expire after 1 hours. 

12 hours later, they're still here (i checked in uploaded-files folder) 

Does anyone know why ? 

Thanks !

**Comment by epoupon** [comment]
I found a bug, but just to be sure: if you restart the service, are the files getting deleted?
Do you see something special in the logs?

**Comment by antoine2tt** [comment]
Hello,

I'm using docker, how can i apply this update you've made ? 

Are you going to upload the docker image as well ? 

Thanks a lot !

**Comment by epoupon** [comment]
For now, you will have to wait for the docker build to complete (it is quite long (few hours) since compilation for arm archs is emulated).
Did you try to start/stop the current docker container to check the files are properly deleted?

**Comment by antoine2tt** [comment]
Hi,

I could't try that, watchtower has updated my container. 
But now, my files are getting deleted so 👍 

Thanks !
