### ISSUE TITLE
If I map '/var/fileshelter' from inside container, it fails to start

### ISSUE THREAD

**Issue by SmartPhoneLover** [epoupon/fileshelter#60]
As described in the title, when I try to map the '/var/fileshelter' directory from inside the container, to the host, FileShelter fails to start, showing the following error:

`Caught std::exception: filesystem error: cannot create directories: Permission denied [/var/fileshelter/uploaded-files]`

**Comment by epoupon** [comment]
Did you properly set up rights on the host's directory?
What command line do you use to start the container?

**Comment by epoupon** [comment]
Feel free to reopen if you have further info

**Comment by SmartPhoneLover** [comment]
> Did you properly set up rights on the host's directory? What command line do you use to start the container?

Ohh, sorry. I forgot to reply to you. I have successfully installed it on my server. That's how (unRAID):

_-v '/mnt/user/appdata/fileshelter/fileshelter.conf':'/etc/fileshelter.conf':'ro'_
