### ISSUE TITLE
download speed

### ISSUE THREAD

**Issue by vetal20600** [epoupon/fileshelter#7]
I have tried you nice application.
Don't you know if there are any download speed issue?
It is too slow on large files. I am guessing why

**Comment by epoupon** [comment]
Hello,

I just tested on a 1.4GB file on my server, I managed to download the file in a few seconds, using the full bandwidth of my gigabit home network. I am using an https version behind a reverse nginx proxy.

Could you please tell me more about your problem? What it is happening exactly?

**Comment by vetal20600** [comment]
I am using javascript to start download automatically.
Can this be a cause?

javascript:
`setTimeout('window.location = 'yoururltofile.file', 5000);`
where 'yoururltofile.file' is:
`ShareResource *newResource = new ShareResource( share->getDownloadUUID() );`
to run javascript:
`wApp->doJavaScript('javascript_command')`

**Comment by epoupon** [comment]
Hello,
Not sure javascript is the culprit. Could you tell more about your environment?

**Comment by vetal20600** [comment]
I am using Ubuntu 16.04.1 LTS.
What exactly information you want? I can check.
There is one more thing. The uploading is faster than downloading for me. 
Like x2/x3 time faster.

**Comment by epoupon** [comment]
Are you testing on your local network? Are you testing locally on the same computer that hosts the application?
What are the download and upload speed you get?

**Comment by vetal20600** [comment]
There is Ubuntu VPS server that I use.
I didn't install and try on my local machine yet.
Upload speed is 3.2 Megabyte per second. Download speed is 300-400 kilobyte per second.

**Comment by epoupon** [comment]
Do you have more information about your problem?
Can you confirm or infirm it is related to fileshelter?

**Comment by vetal20600** [comment]
I can not get confirmation that cause is fileshelter itself. Sometimes it is fast. Sometimes it is slower. Maybe it's hardware issue.

**Comment by epoupon** [comment]
Since it is an VPS instance, maybe you don't get any minimal bandwidth guarantee and it is shared across other users?

**Comment by vetal20600** [comment]
I will check your suggestions. Thanks:)
