### ISSUE TITLE
Demo URL expired and is linking to malicious websites

### ISSUE THREAD

**Issue by gigastackcat** [epoupon/fileshelter#70]
Title. Probably should take down the URL in case someone gets something nasty.

**Comment by epoupon** [comment]
Which one? https://fileshelter-demo.poupon.dev/ seems to work fine for me?

**Comment by epoupon** [comment]
Ah looks like the older domain poupon.io is indeed now used for questionable things...

**Comment by gigastackcat** [comment]
I thought there was the only one demo URL in the description, I didn't see the other in the About. My bad.

**Comment by epoupon** [comment]
But still you are right, this URL must be changed in README.md
