### ISSUE TITLE
compilation errors on OpenBSD arm platform

### ISSUE THREAD

**Issue by ppyyu** [epoupon/fileshelter#72]
Any advice for me to move forward appreciated!  Not knowing C++ I had fixed 2 other compile errors and like to have this running on OpenBSD!

% DEBUG=1 make
[ 22%] Built target fileshelterutils
Consolidate compiler generated dependencies of target filesheltershare
[ 25%] Building CXX object src/libs/share/CMakeFiles/filesheltershare.dir/impl/Db.cpp.o
[ 28%] Building CXX object src/libs/share/CMakeFiles/filesheltershare.dir/impl/File.cpp.o
[ 31%] Building CXX object src/libs/share/CMakeFiles/filesheltershare.dir/impl/Share.cpp.o
[ 34%] Building CXX object src/libs/share/CMakeFiles/filesheltershare.dir/impl/ShareCleaner.cpp.o
[ 37%] Building CXX object src/libs/share/CMakeFiles/filesheltershare.dir/impl/ShareManager.cpp.o
fileshelter/src/libs/share/impl/ShareManager.cpp:45:20: error: reference to 'Share' is ambiguous
        shareToDesc(const Share::Share& share)
                          ^
fileshelter/src/libs/share/impl/ShareCleaner.hpp:27:11: note: candidate found by name lookup is 'Share'
namespace Share
          ^
fileshelter/src/libs/share/impl/ShareCleaner.hpp:30:8: note: candidate found by name lookup is 'Share::Share'
        class Share;
              ^
fileshelter/src/libs/share/impl/ShareManager.cpp:58:4: error: reference to 'Share' is ambiguous
                        Share::FileDesc fileDesc;
                        ^
fileshelter/src/libs/share/impl/ShareCleaner.hpp:27:11: note: candidate found by name lookup is 'Share'
namespace Share
          ^
fileshelter/src/libs/share/impl/ShareCleaner.hpp:30:8: note: candidate found by name lookup is 'Share::Share'
        class Share;
              ^
2 errors generated.
*** Error 1 in . (src/libs/share/CMakeFiles/filesheltershare.dir/build.make:132 'src/libs/share/CMakeFiles/filesheltershare.dir/impl/ShareManager.cpp.o')
*** Error 2 in . (CMakeFiles/Makefile2:998 'src/libs/share/CMakeFiles/filesheltershare.dir/all': make -s -f src/libs/share/CMakeFiles/filesh...)
*** Error 2 in fileshelter/build (Makefile:146 'all': make -s -f CMakeFiles/Makefile2 all)!

**Comment by epoupon** [comment]
I can't test right now but try `const ::Share::Share&` line 45?

**Comment by ppyyu** [comment]
With your suggestion, got it to compile - see below for other changes to get it compile on OpenBSD.
Still doesn't run though, dying with SIGBUS Bus error.
Appreciate if you have any guess - below are 1/ running without gdb, 2/ with gdb.

=== without gdb
% doas -u _fileshelter /usr/local/bin/fileshelter
ARG = /usr/local/bin/fileshelter
ARG = --config=/tmp/fileshelter/wt_config.xml
ARG = --docroot=/usr/local/share/fileshelter/docroot/;/resources,/css,/images,/js,/favicon.ico
ARG = --approot=/usr/local/share/fileshelter/approot
ARG = --deploy-path=/
ARG = --resources-dir=/usr/local/share/Wt/resources
ARG = --http-port=12345
ARG = --http-address=192.168.2.10
ARG = --threads=2
[2022-Nov-01 09:36:19.496] 47378 - [info] "config: reading Wt config file: /tmp/fileshelter/wt_config.xml (location = '/usr/local/bin/fileshelter')"
Bus error

=== with gdb
% doas -u root gdb /usr/local/bin/fileshelter
(gdb) run
Starting program: /usr/local/bin/fileshelter
ARG = /usr/local/bin/fileshelter
ARG = --config=/tmp/fileshelter/wt_config.xml
ARG = --docroot=/usr/local/share/fileshelter/docroot/;/resources,/css,/images,/js,/favicon.ico
ARG = --approot=/usr/local/share/fileshelter/approot
ARG = --deploy-path=/
ARG = --resources-dir=/usr/local/share/Wt/resources
ARG = --http-port=12345
ARG = --http-address=192.168.2.10
ARG = --threads=2
[2022-Nov-01 09:34:17.199] 82426 - [info] "config: reading Wt config file: /tmp/fileshelter/wt_config.xml (location = '/usr/local/bin/fileshelter')"

Program received signal SIGBUS, Bus error.
0x4cfaa564 in Share::Db::getTLSSession () from /usr/local/lib/libfilesheltershare.so
(gdb) bt
#0  0x4cfaa564 in Share::Db::getTLSSession () from /usr/local/lib/libfilesheltershare.so
#1  0x4cfcf264 in Share::ShareCleaner::checkExpiredShares () from /usr/local/lib/libfilesheltershare.so
#2  0x4cfcf044 in Share::ShareCleaner::ShareCleaner () from /usr/local/lib/libfilesheltershare.so
#3  0x4cfd9b60 in Share::ShareManager::ShareManager () from /usr/local/lib/libfilesheltershare.so
#4  0x4cfd9aec in Share::createShareManager () from /usr/local/lib/libfilesheltershare.so
#5  0x0cb758b0 in main () from /usr/local/bin/fileshelter

=== diff to compile successfully on OpenBSD
diff -r libs/share/impl/Db.cpp ../../fileshelter-5.1.0/src/libs/share/impl/Db.cpp
22d21
< #include <unordered_map>
diff -r libs/share/impl/ShareManager.cpp ../../fileshelter-5.1.0/src/libs/share/impl/ShareManager.cpp
45c45
<       shareToDesc(const ::Share::Share& share)
---
>       shareToDesc(const Share::Share& share)
58c58
<                       ::Share::FileDesc fileDesc;
---
>                       Share::FileDesc fileDesc;
diff -r libs/utils/impl/ZipperResourceHandler.cpp ../../fileshelter-5.1.0/src/libs/utils/impl/ZipperResourceHandler.cpp
39c39
<       const std::size_t nbWrittenBytes {static_cast<size_t>(_zipper->writeSome(buffer.data(), buffer.size()))};
---
>       const std::size_t nbWrittenBytes {_zipper->writeSome(buffer.data(), buffer.size())};

**Comment by ppyyu** [comment]
Compiling in Debug mode lets me run without error!
For my use I'm fine running it with debug symbols.  I can help test more if you have additional advice!

**Comment by epoupon** [comment]
Will close this as the first post error is corrected on 5.1.1
