### ISSUE TITLE
Margin disappeared between input and button

### ISSUE THREAD

**Issue by laurens94** [epoupon/fileshelter#85]
It seems the margin between the password input and unlock button is gone since the upgrade to Bootstrap 5:

<img width="663" alt="image" src="https://github.com/epoupon/fileshelter/assets/5780704/72879fc6-4ecb-47c3-9fc8-1eeeb7d00330">

**Comment by epoupon** [comment]
Ah yes good catch, forgot to migrate this one (as well as the download password)
